account/urls.py
from django.urls import path
from django.contrib.auth import views
from .views import (
    ArticleDelete,
    Home ,
    ArticleCreate ,
    ArticleUpdate ,
    ArticleDelete ,
    Profile ,
                    )

app_name = 'account'
urlpatterns = [
    path('home' , Home.as_view() , name='home') ,
    path('article/create' , ArticleCreate.as_view() , name="article_create" ) , 
    path('article/update/<int:pk>' , ArticleUpdate.as_view() , name="article_update" ) , 
    path('article/delete/<int:pk>' , ArticleDelete.as_view() , name="article_delete" ) , 
    path('profile/' , Profile.as_view() , name="profile" ) , 
]

config/urls.py
from django.contrib import admin
from django.urls import path , include 
from django.conf.urls.static import static
from django.conf import settings
from account.views import Login ,Signup,activate


urlpatterns = [
    path('' , include('article.urls')),
    #login and forgar password user
    path('' , include('django.contrib.auth.urls')),
    path("login/", Login.as_view(), name="login"),
    #signup user
    path("signup/", Signup.as_view(), name='signup'),
    #path('activate/(?P<uidb64>[0-9A-Za-z_\\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate'),
    path('activate/<str:uidb64>/<str:token>/', activate, name='activate'),
    #----#
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('account/' , include('account.urls')),
    path('admin/', admin.site.urls),
    path('comment/', include('comment.urls')),
] + static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

templates/partials/category_loop.html
<ul class="navbar-nav ms-auto py-4 py-lg-0">
    {% for cat in cat.children.active  %}
      <li class="nav-item">
        <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'category' slug=cat.slug %}">{{ cat.title }}</a>
        {% if  cat.children.active %}
            {% include "partials/category_loop.html" %}
        {% endif %}
      </li>
    {% endfor %}
  </ul>

templates/partials/category_navbar.html
{% load static %}
<link href="{% static 'css/category_navbar/navbar.css' %}" rel="stylesheet" />
<div class="collapse navbar-collapse nav" id="navbarResponsive">
    <ul class="navbar-nav ms-auto py-4 py-lg-0 ">
        <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href=" {% url 'ArticleList' %}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href=" {% url 'account:home' %}">Account</a>
        </li>
        {% for cat in category  %}
            {% if cat.parent == None %}
                <li class="nav-item ">
                    <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'category' slug=cat.slug %}">
                        {{ cat.title }}
                    </a>
                    {% if cat.children.active %}
                        {% include "partials/category_loop.html" %}
                    {% endif %}  
                </li>
            {% endif %}
        {% endfor %}
    </ul>
        <form class="search-form" action="{% url 'search' %}">
            <input type="text" name="q" class="form-control" placeholder="جست و جوی متن" >
            <button class="btn btn-success" >
                جست و جو  :
            </button>
        </form>
</div>

templates/partials/link.html
<a href="{% url link %}" class="nav-link {% if request.resolver_match.url_name == link_name %} active {% endif %}">
    <i class="fa {{ classes }} nav-icon"></i>
    <p> {{ content }} </p>
</a>